# yaml-language-server: $schema=../../bundles/subscription/schema.json
apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: mars-asterix-dev
  uuid: 81a76698-eb4d-4e2e-b9d8-a1a355956ba9
spec:
  source: /bundles/subscription
  inputs:
    tenant: mars
    project: asterix
    stage: dev

    resource_providers:
      - "Microsoft.Network"

    iam_admin_users:
      - "admin@example.org"

    iam_readonly_users:
      - "cto@example.org"

    network_cidr_range: "192.168.1.0/24"

    firewall_internet_allowed_fqdns:
      - "terramate.io"
      - "example.org"
