# yaml-language-server: $schema=../bundles/subscription/schema.json
apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: mars-asterix
  uuid: 81a76698-eb4d-4e2e-b9d8-a1a355956ba9
spec:
  source: /bundles/subscription
  inputs:
    tenant: mars
    project: asterix

    resource_providers:
      - "Microsoft.Network"

    iam_admin_users:
      - "admin@example.org"

    iam_readonly_users:
      - "cto@example.org"

    firewall_internet_allowed_fqdns:
      - "terramate.io"
      - "example.org"

environments:
  dev:
    inputs:
      network_cidr_range: "192.168.1.0/24"

  prd:
    inputs:
      network_cidr_range: "192.168.2.0/24"
